### GET
GET http://localhost:3001/api/blogs




### POST
POST http://localhost:3001/api/blogs
content-type: application/json

# author, url, title, likes
{
  "author": "Jouni M",
  "url": "http://www.example.com",
  "title": "Jonen Blogi",
  "likes": 0
}


### GET by PK
GET http://localhost:3001/api/blogs/5


### DELETE
DELETE http://localhost:3001/api/blogs/3
