### GET
GET http://localhost:3001/api/blogs


### GET by search string
GET http://localhost:3001/api/blogs?search=jone





### POST
POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvdW5pLm1hbm5pc3RvQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MjE3MjgyNTF9.gMj6nDhdnvKUmN-nTDrXpa0kvpLuqEOBPcGCPUms4AQ

{
  "author": "Teppo Testaaja",
  "url": "http://www.example.com",
  "title": "Tech blog post 2",
  "likes": 1,
  "year": 2024
}


### GET by PK
GET http://localhost:3001/api/blogs/5


### DELETE
DELETE http://localhost:3001/api/blogs/4
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvdW5pLm1hbm5pc3RvQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MjE3MjgyNTF9.gMj6nDhdnvKUmN-nTDrXpa0kvpLuqEOBPcGCPUms4AQ


### PUT
PUT http://localhost:3001/api/blogs/1
content-type: application/json

  {
    "likes": 8
  }


### POST with invalid data
POST http://localhost:3001/api/blogs
content-type: application/json

{
  "author": null
}


### PUT without likes
PUT http://localhost:3001/api/blogs/9
content-type: application/json

{
  "likes": 20
}