

### GET
GET http://localhost:3001/api/users


### GET by id
GET http://localhost:3001/api/users/1


### POST
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "jouni.mannisto@gmail.com",
    "name": "Teppo T"
}

### PUT by username
PUT http://localhost:3001/api/users/jouni
content-type: application/json

{
    "name": "JouniM"
}



### POST with invalid data
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "jouni",
    "name": "Jouni M"
}

### POST another user
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "teppo@example.com",
    "name": "Teppo Testaaja M"
}