
### LOGIN (success)
POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "jouni.mannisto@gmail.com",
    "password": "salainen"
}

### LOGIN (fail)
POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "jouni.mannisto@gmail.com",
    "password": "wrong one"
}

### DELETE (logout)
DELETE http://localhost:3001/api/logout
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvdW5pLm1hbm5pc3RvQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MjE4MDIzMjZ9.BWmzEJGU0H9GeeopF_ElxZx4mXLxI1QweHe557WLabg