### GET
GET http://localhost:3001/api/readinglists


### POST new reading list item
POST http://localhost:3001/api/readinglists
content-type: application/json

{
  "blogId": 2,
  "userId": 2
}


### PUT
PUT http://localhost:3001/api/readinglists/1
content-type: application/json
Authorization: Bearer zyx
{
  "read": true
}