### GET
GET http://localhost:3001/api/readinglists


### POST new reading list item
POST http://localhost:3001/api/readinglists
content-type: application/json

{
  "blogId": 1,
  "userId": 2
}


### PUT
PUT http://localhost:3001/api/readinglists/2
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvdW5pLm1hbm5pc3RvQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MjE4MDIzMjZ9.BWmzEJGU0H9GeeopF_ElxZx4mXLxI1QweHe557WLabg

{
  "read": false
}